config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :days
  resources :application

  root to: "welcome#index"

  get '/stats' => 'pages#stats'
  get '/about' => 'pages#about'
  get '/home' => 'pages#home'

end

app/models/day.rb
class Day < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "600x600>", thumb: "200x200#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :days

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # call the strong params
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    home_url
  end

  #strong parameters method so users cant change specific db cols
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me)}
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me)}
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  # GET /days
  # GET /days.json
  def index
    @days = Day.all
  end

  def home
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = current_user.days.build
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = current_user.days.build(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render :show, status: :created, location: @day }
        format.js
      else
        format.html { render :new }
        format.json { render json: @day.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    @day = Day.find(params[:id])
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { render :show, status: :ok, location: @day }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @day.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url, notice: 'Day was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:date, :description, :image, :rating)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def stats
  end

  def about
  end

  def home
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #helps to show current menu item
  def cp(path)
    current_route = Rails.application.routes.recognize_path(path)
    "active" if current_page?(path)
  end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/days/_day.html.erb
<div class="timeline-badge" id="inner_<%= day.date %>">
  <span class="timeline-balloon-date-day" style="display:block;"><%= day.date.day %></span>
  <span class="timeline-balloon-date-month"><%= day.date.strftime("%b") %></span>
</div>
<div class="timeline-panel">

  <div class="timeline-body">
    <div class="timeline-left">
      <%= image_tag( day.image.url(:thumb), class: "day-img") %>
    </div>
    <div class="timeline-content">

      <p class="day-text">&quot;<%= day.description %>&quot;</p>
      <p class="day-short-rating"> <%= day.rating %>
         <span class="glyphicon glyphicon-star single-star"></span><%= link_to 'Edit', edit_day_path(day) %><%= link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' } %></p>

    </div>
  </div>
</div>

app/views/days/_dayempty.html.erb
  <div class="timeline-badge">
    <span class="timeline-balloon-date-day" style="display:block;"><%= date.strftime("%d") %></span>
    <span class="timeline-balloon-date-month"><%= date.strftime("%b") %></span>
  </div>
  <div class="timeline-panel">

    <div class="timeline-body">
      <div class="timeline-left">
      </div>
      <div class="timeline-content">

        <a href="/days/new?date=<%= date.strftime('%Y-%m-%d') %>" data-remote="true" id="new_day_ajax_<%= date.strftime('%Y-%m-%d') %>"><p class="day-text">Add This day</p></a>

        <p class="day-short-rating"></p>

      </div>
    </div>
  </div>

app/views/days/_form.html.erb
<%= form_for @day, html: {multipart: true}, remote: true do |f| %>
  <% if @day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% @day.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="float:left;">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, input_html: {maxlength: 140}%>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field" style="float:right;">
    <%= f.label :rating %><br>
    <%= f.number_field :rating, min:1, max:10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/days/create.js.erb
var temp = $('#new_day').closest( 'li' );
$('#new_day').remove();
$(temp).html('<%= j render(@day) %>').hide().fadeIn();

app/views/days/destroy.js.erb
//das klappt
var tmp = $('#inner_<%= @day.date %>').closest('li');
$(tmp).slideUp();
//
//$(tmp).html(' j (render partial: "days/dayempty", locals: {date: date}) %>').hide().fadeIn();

app/views/days/edit.html.erb
<!-- navigation##############################-->
<%= render "partials/navigation" %>

<h1>Editing Day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/edit.js.erb
var a = $('#edit_day_ajax_<%= @day.id %>').closest( 'li' );

$(a).html('<%= j render("form") %>').hide().fadeIn();

app/views/days/home.html.erb
<!-- navigation##############################-->
<%= render "partials/navigation" %>

<!---site-wrap###############################-->
<div class="site-wrap">

  <!-- Content Section -->
  <section class="home-top">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>Hi <%= current_user.email %>, welcome back!</h2>
          <h3> You have missed <a href="#">?</a> day entries last week! Fill them in now.</h3>
        </div>

      </div>
    </div>
  </section>

  <!-- Content Section -->
  <section class="profile-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
        </div>
        <div class="col-lg-12">
          <%= image_tag("ich.jpg", class: "profile-img", alt: "profile picture", width:"200px", height:"200px") %>
          <div class="user-desc">
            <h3><%= current_user.email %><a href="#"><span style="font-size:15px; color: #ccc;" class="glyphicon glyphicon-cog"></span></a></h3>
            <p>Here since: 01/01/01</p>
            <p>314 entries</p>
          </div>
        </div>



      </div>
    </div>
  </section>

  <!-- Content Section -->
  <section class="single-day-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <h3>Have a look at this random day</h3>
        </div>
        <div class="container">
          <div class="timeline-header">
          </div>
          <ul class="timeline">

            <li class="timeline-sinlge">
              <div class="timeline-badge">
                <span class="timeline-balloon-date-day">27</span>
                <span class="timeline-balloon-date-month">Dec</span>
              </div>
              <div class="timeline-panel">

                <div class="timeline-body">
                  <div class="timeline-left">
                    <%= image_tag("tag.jpg", class: "day-img") %>
                  </div>
                  <div class="timeline-content">

                    <p class="day-text">&quot;Today I first did something very stupid, but made the best of it. For lunch i ate something delicious, yum. Best thing was meeting s/o. 4321&quot;</p>
                    <p class="day-short-rating"> 9 <span class="glyphicon glyphicon-star single-star"></span></p>

                  </div>
                </div>
              </div>
            </li>

            <!--timeline end-->
            <li>
              <div class="timeline-end">
                <span class=""></span>
              </div>
            </li>
            <!--/timeline end-->

          </ul>
        </div>
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container -->
  </section>

app/views/days/index.html.erb
<!-- navigation##############################-->
<%= render "partials/navigation" %>

<!---site-wrap###############################-->
<div class="site-wrap">

  <!-- Content Section -->
  <section id="days-title-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h2 style="text-align:center;"><%= Time.now.strftime("%B") %> <%= Time.now.year%></h2>
          <span class="other-months"><a href="#"> <span class="glyphicon glyphicon-chevron-left"></span></a>   <a href="#"><span class="glyphicon glyphicon-chevron-right"></span></a></span>
        </div>
      </div>
    </div>
  </section>

  <!-- Content Section -->
  <section>
    <div class="container">
      <div class="row">
        <div class="container">
          <div class="timeline-header">
          </div>
          <ul class="timeline">

            <%
            start_date = current_user.created_at.to_date
            end_date = Date.today
            end_date.downto(start_date).each do |date|
            %>



                    <%
                      if(@days.exists? date: date)
                        @days.where(date: date).each do |day|

                      %>
                    <li id="li_<%= date.strftime('%Y-%m-%d') %>">
                      <div class="timeline-badge" id="inner_<%= day.date %>">
                        <span class="timeline-balloon-date-day" style="display:block;"><%= day.date.day %></span>
                        <span class="timeline-balloon-date-month"><%= day.date.strftime("%b") %></span>
                      </div>
                      <div class="timeline-panel">

                        <div class="timeline-body">
                          <div class="timeline-left">
                            <%= image_tag( day.image.url(:thumb), class: "day-img") %>
                          </div>
                          <div class="timeline-content">

                            <p class="day-text">&quot;<%= day.description %>&quot;</p>
                            <p class="day-short-rating"> <%= day.rating %>
                               <span class="glyphicon glyphicon-star single-star"></span><%= link_to 'Edit', edit_day_path(day), id: "edit_day_ajax_#{day.id}", remote:true %><%= link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></p>

                          </div>
                        </div>
                      </div>
                    </li>
                    <% end %>
                    <% else %>

                    <li id="li_<%= date.strftime('%Y-%m-%d') %>">
                      <div class="timeline-badge">
                        <span class="timeline-balloon-date-day" style="display:block;"><%= date.strftime("%d") %></span>
                        <span class="timeline-balloon-date-month"><%= date.strftime("%b") %></span>
                      </div>
                      <div class="timeline-panel">

                        <div class="timeline-body">
                          <div class="timeline-left">
                          </div>
                          <div class="timeline-content">

                            <!--<p class="day-text"><%= link_to 'Add this day', new_day_path %></p>-->
                            <a href="/days/new?date=<%= date.strftime('%Y-%m-%d') %>" data-remote="true" id="new_day_ajax_<%= date.strftime('%Y-%m-%d') %>"><p class="day-text">Add This day</p></a>

                            <p class="day-short-rating"></p>

                          </div>
                        </div>
                      </div>
                    </li>

                    <% end %>

            <% end %>

            <!--timeline end-->
            <li>
              <div class="timeline-badge">
                <span class="">more</span>
              </div>
            </li>
            <!--/timeline end-->

          </ul>
        </div>
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container -->
  </section>

app/views/days/new.html.erb
<!-- navigation##############################-->
<%= render "partials/navigation" %>


<h1>New Day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/new.js.erb
//$('#new_day_ajax').hide().after('<%= j render("form")%>');
$('#new_day_ajax_<%= params[:date] %>').hide().after('<%= j render("form")%>');

app/views/days/show.html.erb
<!-- navigation##############################-->
<%= render "partials/navigation" %>

<p>
  <strong>Date:</strong>
  <%= @day.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @day.description %>
</p>

<%= link_to 'Edit', edit_day_path(@day) %> |
<%= link_to 'Back', days_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Felix Gellner">

  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>

  <title>PicoJournal</title>
  <%= favicon_link_tag("favicon-16x16.png") %>

  <!-- fonts-->
  <%= stylesheet_link_tag('application', 'http://fonts.googleapis.com/css?family=Nixie+One', media:'all', 'data-turbolinks-track' => true) %>
  <%= stylesheet_link_tag('application', 'http://fonts.googleapis.com/css?family=Ledger', media:'all', 'data-turbolinks-track' => true) %>

  <!-- Custom CSS -->


</head>

<body>

<%= yield %>

</body>

<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Felix Gellner 2016</p>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
</footer>

</html>

app/views/pages/about.html.erb
<!-- navigation##############################-->
<%= render "partials/navigation" %>

  <!---site-wrap###############################-->
  <div class="site-wrap">

    <!-- Content Section -->
    <section>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <h1>ABOUT</h1>
            <div class="about">
              <p>PicoJournal is under construction since the end of 2015. It is a one man hobby project, I only work on it fridays while simultaneously trying to learn Rails, so don't expect rapid changes ;)
                <br>The first idea of this came to me way earlier in 2011. The following video shares a similar idea, and helped me to stay motivated while constructing this website.</p>
            </div>
            <div class="faq">
              <h2>FAQ</h2>
              <strong>Q: Who are <a href="http://www.felixgellner.de" target="blank">you</a>?</strong>
              <p>A Computer Science student, trying to improve his web development skills with some awesome side projects.</p>
              <strong>Q: Why is this called PicoJournal?</strong>
              <p> Because the website is supposed to appeal to people who like the idea of journaling, but writing a page every day is just too much work for them. Also, Pico is a prefix denoting one trillionth, which is hopefully the amount of effort required
                to use PicoJournal in comparison to a traditional journal :)</p>
              <strong>Q: When will this site be officially completed?</strong>
              <p>I don't know. I plan for progress to be slow but steady.</p>
            </div>

            <h2>Inspiration</h2>
            <!--END FAQ-->
            <p>PicoJournal is partly inspired by a great ted talk from Cesar Kuriyama. So in the case I couldn't fully protray the idea of PicoJournal, this video might help :)</p>
            </br>
            <iframe width="720" height="480" src="http://www.youtube.com/embed/7uN4I1wEOXE" frameborder="0" allowfullscreen></iframe>


          </div>
        </div>
      </div>
    </section>

app/views/pages/home.html.erb
<!-- navigation##############################-->
<%= render "partials/navigation" %>


  <!---site-wrap###############################-->
  <div class="site-wrap">

    <!-- Content Section -->
    <section class="home-top">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2>Hi <%= current_user.username %>, welcome back!</h2>
            <h3> You have missed <%= link_to 'some', new_day_path %> day entries last week! Fill them in now.</h3>
          </div>

        </div>
      </div>
    </section>

    <!-- Content Section -->
    <section class="profile-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
          </div>
          <div class="col-lg-12">
            <%= image_tag("ich.jpg", class: "profile-img", alt: "Profile picture", width:"200px", height:"200px") %>
            <div class="user-desc">
              <h3><%= current_user.username %> <a href="#"><span style="font-size:15px; color: #ccc;" class="glyphicon glyphicon-cog"></span></a></h3>
              <p>Here since: <%= current_user.created_at.strftime("%d.%m.%Y") %></p>
              <p>1337 entries</p>
            </div>
          </div>



        </div>
      </div>
    </section>

    <!-- Content Section -->
    <section class="single-day-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <h3>Have a look at this random day</h3>
          </div>
          <div class="container">
            <div class="timeline-header">
            </div>
            <ul class="timeline">

              <li class="timeline-sinlge">
                <div class="timeline-badge">
                  <span class="timeline-balloon-date-day">27</span>
                  <span class="timeline-balloon-date-month">Dec</span>
                </div>
                <div class="timeline-panel">

                  <div class="timeline-body">
                    <div class="timeline-left">
                      <img class="day-img" src="img/tag.jpg" alt="">
                    </div>
                    <div class="timeline-content">

                      <p class="day-text">&quot;Today I first did something very stupid, but made the best of it. For lunch i ate something delicious, yum. Best thing was meeting s/o. 4321&quot;</p>
                      <p class="day-short-rating"> 9 <span class="glyphicon glyphicon-star single-star"></span></p>

                    </div>
                  </div>
                </div>
              </li>

              <!--timeline end-->
              <li>
                <div class="timeline-end">
                  <span class=""></span>
                </div>
              </li>
              <!--/timeline end-->

            </ul>
          </div>
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container -->
    </section>

app/views/pages/stats.html.erb
<!-- navigation##############################-->
<%= render "partials/navigation" %>

  <!---site-wrap###############################-->
  <div class="site-wrap">

    <!-- Content Section -->
    <section>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <h1>Stats</h1>
            <p>Look at the progression of your days, compare workdays and the weekend and many more fun things.</p>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <h1 id="soon">Not finished yet.</h1>
            <div id="container" style="width: 75%;">
                <canvas id="canvas"></canvas>
            </div>
            <script>
                var MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

                var randomScalingFactor = function() {
                    return (Math.random() > 0.5 ? 1.0 : -1.0) * Math.round(Math.random() * 100);
                };
                var randomColorFactor = function() {
                    return Math.round(Math.random() * 255);
                };
                var randomColor = function() {
                    return 'rgba(' + randomColorFactor() + ',' + randomColorFactor() + ',' + randomColorFactor() + ',.7)';
                };

                var barChartData = {
                    labels: ["January", "February", "March", "April", "May", "June", "July"],
                    datasets: [{
                        label: 'Dataset 1',
                        backgroundColor: "rgba(192,53,70,0.9)",
                        data: [randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor()]
                    }, {
                        hidden: true,
                        label: 'Dataset 2',
                        backgroundColor: "rgba(192,53,70,0.9)",
                        data: [randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor()]
                    }, {
                        label: 'Dataset 3',
                        backgroundColor: "rgba(192,53,70,0.9)",
                        data: [randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor()]
                    }]

                };

                window.onload = function() {
                    var ctx = document.getElementById("canvas").getContext("2d");
                    window.myBar = new Chart(ctx, {
                        type: 'bar',
                        data: barChartData,
                        options: {
                            // Elements options apply to all of the options unless overridden in a dataset
                            // In this case, we are setting the border of each bar to be 2px wide and green
                            elements: {
                                rectangle: {
                                    borderWidth: 2,
                                    borderColor: 'rgb(192, 53, 70)',
                                    borderSkipped: 'bottom'
                                }
                            },
                            responsive: true,
                            legend: {
                                position: 'top',
                            },
                            title: {
                                display: true,
                                text: 'Bar Chart Test'
                            }
                        }
                    });

                };

                $('#randomizeData').click(function() {
                    var zero = Math.random() < 0.2 ? true : false;
                    $.each(barChartData.datasets, function(i, dataset) {
                        dataset.backgroundColor = randomColor();
                        dataset.data = dataset.data.map(function() {
                            return zero ? 0.0 : randomScalingFactor();
                        });

                    });
                    window.myBar.update();
                });

                $('#addDataset').click(function() {
                    var newDataset = {
                        label: 'Dataset ' + barChartData.datasets.length,
                        backgroundColor: randomColor(),
                        data: []
                    };

                    for (var index = 0; index < barChartData.labels.length; ++index) {
                        newDataset.data.push(randomScalingFactor());
                    }

                    barChartData.datasets.push(newDataset);
                    window.myBar.update();
                });

                $('#addData').click(function() {
                    if (barChartData.datasets.length > 0) {
                        var month = MONTHS[barChartData.labels.length % MONTHS.length];
                        barChartData.labels.push(month);

                        for (var index = 0; index < barChartData.datasets.length; ++index) {
                            //window.myBar.addData(randomScalingFactor(), index);
                            barChartData.datasets[index].data.push(randomScalingFactor());
                        }

                        window.myBar.update();
                    }
                });

                $('#removeDataset').click(function() {
                    barChartData.datasets.splice(0, 1);
                    window.myBar.update();
                });

                $('#removeData').click(function() {
                    barChartData.labels.splice(-1, 1); // remove the label first

                    barChartData.datasets.forEach(function(dataset, datasetIndex) {
                        dataset.data.pop();
                    });

                    window.myBar.update();
                });
            </script>
          </div>
        </div>
      </div>
    </section>

app/views/partials/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-top my-nav logged-in-nav" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "/days", :class => "navbar-brand brand" do %>
        <span class="pico">Pico</span><span class="journal">Journal</span>
      <% end %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Home', home_url, class: cp('/home') %>
        </li>
        <li>
          <%= link_to 'Days', days_url, class: cp('/days')  %>
        </li>
        <li>
          <%= link_to 'Stats', stats_url, class: cp('/stats')  %>
        </li>
        <li>
          <%= link_to 'About', about_url, class: cp('/about')  %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"></span> <%= current_user.username %></a>
          <ul class="dropdown-menu">
            <li><a href="#">Settings</a></li>
            <li><a style="color: #ccc !important;" href="#">Go Premium</a></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method=> 'delete' %></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>